
'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'nl' | 'en' | 'de' | 'fr' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  nl: {
    nav_home: 'Home',
    nav_tour: 'Tour',
    nav_galleries: 'Zalen',
    nav_your_room: 'Uw Zaal',
    nav_shop: 'Winkel',
    nav_about: 'Over',
    nav_contact: 'Contact',
    nav_admin: 'Beheer',
    nav_collections: 'Collecties',
    nav_privacy: 'Privacy',
    nav_guide_click: 'Klik voor Gids',
    shop_title: 'Museumwinkel',
    shop_subtitle: 'Haal een Sterk in huis',
    shop_intro: 'Hoogwaardige reproducties, van ansichtkaart tot Fine Art print.',
    shop_postcard: 'Ansichtkaart',
    shop_poster: 'Poster',
    shop_print: 'Fine Art Print',
    shop_digital: 'Digitale Download',
    shop_order_now: 'Nu Bestellen',
    shop_order_form: 'Bestelformulier',
    shop_add_to_cart: 'In Winkelwagen',
    shop_details: 'Product Details',
    shop_format: 'Formaat',
    shop_price: 'Prijs',
    shop_order_success: 'Bestelling Ontvangen',
    shop_order_desc: 'Bedankt voor uw bestelling. Wij nemen via e-mail contact met u op voor de afhandeling en verzending.',
    order_label_name: 'Naam',
    order_label_email: 'E-mail',
    order_label_address: 'Adres & Postcode',
    order_button_confirm: 'Bevestig Bestelling',
    footer_rights: 'Alle rechten voorbehouden.',
    hero_start_walk: 'Begin de Wandeling',
    hero_your_room: 'Stel uw eigen zaal samen',
    hero_subtitle: 'Digitale Collectie',
    gallery_select: 'Kies een Zaal',
    gallery_closed: 'Deze zaal is momenteel niet toegankelijk.',
    curator_title: 'Uw eigen expositie',
    curator_subtitle: 'Curator van het Retrospectief',
    curator_clear: 'Filters wissen',
    curator_open: 'Open Zaal',
    curator_other: 'Overig',
    curator_no_results: 'Geen werken gevonden voor deze combinatie.',
    viewer_room: 'Zaal',
    viewer_unknown_year: 'Jaartal onbekend',
    viewer_prev: 'Vorige',
    viewer_next: 'Volgende',
    viewer_show_info: 'Toon informatie',
    viewer_hide_info: 'Verberg informatie',
    viewer_unknown: 'Interactief',
    viewer_hint_zoom: 'Scroll of dubbelklik voor vrije zoom',
    end_of_room: 'Einde van deze zaal',
    prev_room: 'Vorige Zaal',
    next_room: 'Volgende Zaal',
    all_works: 'Alle werken',
    contact_label_name: 'Naam',
    contact_label_email: 'E-mail',
    contact_label_subject: 'Onderwerp',
    contact_label_message: 'Bericht / Herinnering',
    contact_button_send: 'Verstuur Bericht',
    contact_phone: 'Telefoon',
    contact_location: 'Locatie',
    contact_loc_value: 'Noord-Holland, Nederland',
    contact_success_title: 'Bericht Verzonden',
    contact_success_desc: 'Bedankt voor uw bericht. We nemen zo snel mogelijk contact met u op.',
    contact_placeholder_name: 'Uw naam',
    contact_placeholder_email: 'uw@email.nl',
    contact_placeholder_subject: 'Waar gaat het over?',
    contact_placeholder_message: 'Uw verhaal of vraag...',
    guide_welcome: 'Welkom in het Digitaal Retrospectief',
    guide_intro: 'Dit museum is een levend archief. Een plek waar de essentie van Licht, Ruimte en Water wordt bewaard voor de toekomst.',
    guide_concept_title: 'Het Concept',
    guide_concept_quote: '"Het oeuvre van Thijs Sterk (1913-1982) omvat meer dan 325 werken. Dit platform ontsluit de collectie in museale kwaliteit, waarbij elk detail tot op de verfkorrel bestudeerd kan worden via onze Deep Zoom technologie."',
    guide_nav_title: 'Navigatie Gids',
    guide_nav_tour_label: 'De Tour',
    guide_nav_tour_desc: 'Een meeslepende, horizontale wandeling door de zalen. Gebruik uw muis, de knoppen onderin of de pijltjestoetsen om te wandelen.',
    guide_nav_galleries_label: 'Zalen',
    guide_nav_galleries_desc: 'Directe toegang tot thematische collecties zoals \'Polder\', \'Bretagne\' of \'Monumentaal\'.',
    guide_nav_curator_label: 'Uw Zaal (Curator)',
    guide_nav_curator_desc: 'Stel uw eigen expositie samen. Combineer tags zoals \'Olieverf\' en \'Haven\' om uw persoonlijke selectie te tonen.',
    guide_nav_shop_label: 'Winkel',
    guide_nav_shop_desc: 'Haal een \'Sterk\' in huis. Van hoogwaardige posters tot gecertificeerde Fine Art prints.',
    guide_viewer_title: 'De Viewer (Deep Zoom)',
    guide_viewer_zoom_label: 'De Grote Loep (+/-)',
    guide_viewer_zoom_desc: 'Onze krachtigste tool. Zoomt met één klik direct 5x in op de details van het schilderij.',
    guide_viewer_info_label: 'Informatie (i)',
    guide_viewer_info_desc: 'Toont de verborgen informatiebalk met het jaartal, de techniek en de afmetingen van het werk.',
    guide_viewer_browse_label: 'Snel Bladeren',
    guide_viewer_browse_desc: 'Gebruik de pijlen links en rechts om naar het volgende werk in de zaal te gaan zonder de viewer te sluiten.',
    guide_controls_title: 'Bediening & Sneltoetsen',
    guide_controls_esc: 'Viewer Sluiten',
    guide_controls_arrows: 'Wandelen / Bladeren',
    guide_controls_scroll: 'Vrij Inzoomen',
    guide_controls_click: 'Detail focus',
    guide_footer: 'Een leven gewijd aan de essentie van het licht.',
  },
  en: {
    nav_home: 'Home',
    nav_tour: 'Tour',
    nav_galleries: 'Galleries',
    nav_your_room: 'Your Room',
    nav_shop: 'Shop',
    nav_about: 'About',
    nav_contact: 'Contact',
    nav_admin: 'Admin',
    nav_collections: 'Collections',
    nav_privacy: 'Privacy',
    nav_guide_click: 'Click for Guide',
    shop_title: 'Museum Shop',
    shop_subtitle: 'Bring a Sterk into your home',
    shop_intro: 'High-quality reproductions, from postcards to Fine Art prints.',
    shop_postcard: 'Postcard',
    shop_poster: 'Poster',
    shop_print: 'Fine Art Print',
    shop_digital: 'Digital Download',
    shop_order_now: 'Order Now',
    shop_order_form: 'Order Form',
    shop_add_to_cart: 'Add to Cart',
    shop_details: 'Product Details',
    shop_format: 'Format',
    shop_price: 'Price',
    shop_order_success: 'Order Received',
    shop_order_desc: 'Thank you for your order. We will contact you via email for payment and shipping.',
    order_label_name: 'Name',
    order_label_email: 'Email',
    order_label_address: 'Address & Postal Code',
    order_button_confirm: 'Confirm Order',
    footer_rights: 'All rights reserved.',
    hero_start_walk: 'Start the Walk',
    hero_your_room: 'Curate your own room',
    hero_subtitle: 'Digital Collection',
    gallery_select: 'Choose a Gallery',
    gallery_closed: 'This gallery is currently closed.',
    curator_title: 'Your own exhibition',
    curator_subtitle: 'Curator of the Retrospective',
    curator_clear: 'Clear filters',
    curator_open: 'Open Room',
    curator_other: 'Other',
    curator_no_results: 'No works found for this combination.',
    viewer_room: 'Room',
    viewer_unknown_year: 'Year unknown',
    viewer_prev: 'Previous',
    viewer_next: 'Next',
    viewer_show_info: 'Show information',
    viewer_hide_info: 'Hide information',
    viewer_unknown: 'Interactive',
    viewer_hint_zoom: 'Scroll or double-click for free zoom',
    end_of_room: 'End of this gallery',
    prev_room: 'Previous Room',
    next_room: 'Next Room',
    all_works: 'All works',
    contact_label_name: 'Name',
    contact_label_email: 'Email',
    contact_label_subject: 'Subject',
    contact_label_message: 'Message / Memory',
    contact_button_send: 'Send Message',
    contact_phone: 'Phone',
    contact_location: 'Location',
    contact_loc_value: 'North Holland, Netherlands',
    contact_success_title: 'Message Sent',
    contact_success_desc: 'Thank you for your message. We will contact you as soon as possible.',
    contact_placeholder_name: 'Your name',
    contact_placeholder_email: 'your@email.com',
    contact_placeholder_subject: 'What is it about?',
    contact_placeholder_message: 'Your story or question...',
    guide_welcome: 'Welcome to the Digital Retrospective',
    guide_intro: 'This museum is a living archive. A place where the essence of Light, Space, and Water is preserved for the future.',
    guide_concept_title: 'The Concept',
    guide_concept_quote: '"The oeuvre of Thijs Sterk (1913-1982) comprises more than 325 works. This platform makes the collection accessible in museum quality, where every detail can be studied down to the grain of paint through our Deep Zoom technology."',
    guide_nav_title: 'Navigation Guide',
    guide_nav_tour_label: 'The Tour',
    guide_nav_tour_desc: 'An immersive, horizontal walk through the galleries. Use your mouse, the buttons at the bottom, or the arrow keys to walk.',
    guide_nav_galleries_label: 'Galleries',
    guide_nav_galleries_desc: 'Direct access to thematic collections such as \'Polder\', \'Brittany\', or \'Monumental\'.',
    guide_nav_curator_label: 'Your Room (Curator)',
    guide_nav_curator_desc: 'Curate your own exhibition. Combine tags like \'Oil paint\' and \'Harbor\' to display your personal selection.',
    guide_nav_shop_label: 'Shop',
    guide_nav_shop_desc: 'Bring a \'Sterk\' into your home. From high-quality posters to certified Fine Art prints.',
    guide_viewer_title: 'The Viewer (Deep Zoom)',
    guide_viewer_zoom_label: 'The Big Lens (+/-)',
    guide_viewer_zoom_desc: 'Our most powerful tool. Zooms in 5x on the details of the painting with a single click.',
    guide_viewer_info_label: 'Information (i)',
    guide_viewer_info_desc: 'Shows the hidden information bar with the year, technique, and dimensions of the work.',
    guide_viewer_browse_label: 'Quick Browse',
    guide_viewer_browse_desc: 'Use the left and right arrows to move to the next work in the gallery without closing the viewer.',
    guide_controls_title: 'Controls & Shortcuts',
    guide_controls_esc: 'Close Viewer',
    guide_controls_arrows: 'Walk / Browse',
    guide_controls_scroll: 'Free Zoom',
    guide_controls_click: 'Detail focus',
    guide_footer: 'A life dedicated to the essence of light.',
  },
  de: {
    nav_home: 'Home',
    nav_tour: 'Tour',
    nav_galleries: 'Galerien',
    nav_your_room: 'Ihr Saal',
    nav_shop: 'Laden',
    nav_about: 'Über',
    nav_contact: 'Kontakt',
    nav_admin: 'Beheer',
    nav_guide_click: 'Hier klicken für Hilfe',
    shop_title: 'Museumsshop',
    shop_subtitle: 'Holen Sie sich einen Sterk nach Hause',
    shop_postcard: 'Postkarte',
    shop_poster: 'Poster',
    shop_print: 'Kunstdruck',
    shop_digital: 'Digitaler Download',
    shop_order_now: 'Jetzt Bestellen',
    shop_order_success: 'Bestellung erhalten',
    footer_rights: 'Alle Rechte vorbehalten.',
    hero_start_walk: 'Wanderung beginnen',
    hero_subtitle: 'Digitale Sammlung',
    curator_other: 'Andere',
    all_works: 'Alle Werke',
    guide_welcome: 'Willkommen in der digitalen Retrospektive',
    guide_concept_title: 'Das Konzept',
    guide_nav_title: 'Navigationshilfe',
  },
  fr: {
    nav_home: 'Accueil',
    nav_tour: 'Visite',
    nav_galleries: 'Salles',
    nav_your_room: 'Votre Salle',
    nav_shop: 'Boutique',
    nav_about: 'À propos',
    nav_contact: 'Contact',
    nav_guide_click: 'Guide du Musée',
    shop_title: 'Boutique du Musée',
    shop_postcard: 'Carte postale',
    shop_poster: 'Poster',
    shop_print: 'Impression d\'art',
    shop_digital: 'Téléchargement numérique',
    shop_order_now: 'Commander',
    footer_rights: 'Tous droits réservés.',
    hero_start_walk: 'Commencer la visite',
    hero_subtitle: 'Collection numérique',
    curator_other: 'Autre',
    all_works: 'Toutes les œuvres',
    guide_welcome: 'Bienvenue dans la Rétrospective Digitale',
    guide_concept_title: 'Le Concept',
    guide_nav_title: 'Guide de Navigation',
  },
  es: {
    nav_home: 'Inicio',
    nav_tour: 'Visita',
    nav_galleries: 'Galerías',
    nav_your_room: 'Su Sala',
    nav_shop: 'Tienda',
    nav_about: 'Acerca de',
    nav_contact: 'Contacto',
    nav_guide_click: 'Guía del Museo',
    shop_title: 'Tienda del Museo',
    shop_postcard: 'Postal',
    shop_poster: 'Póster',
    shop_print: 'Impresión de arte',
    shop_digital: 'Descarga digital',
    shop_order_now: 'Pedir ahora',
    footer_rights: 'Todos los derechos reservados.',
    hero_start_walk: 'Iniciar la Visita',
    hero_subtitle: 'Colección Digital',
    curator_other: 'Otro',
    all_works: 'Todas las obras',
    guide_welcome: 'Bienvenido a la Retrospectiva Digital',
    guide_concept_title: 'El Concepto',
    guide_nav_title: 'Guía de Navegación',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('nl');

  useEffect(() => {
    const saved = localStorage.getItem('app-lang') as Language;
    if (saved && ['nl', 'en', 'de', 'fr', 'es'].includes(saved)) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app-lang', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || translations['nl'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
