'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'nl' | 'en' | 'de' | 'fr' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  nl: {
    nav_home: 'Home',
    nav_tour: 'Tour',
    nav_galleries: 'Zalen',
    nav_your_room: 'Uw Zaal',
    nav_shop: 'Winkel',
    nav_about: 'Over',
    nav_contact: 'Contact',
    nav_admin: 'Beheer',
    nav_museum_title: 'Digitaal Museum',
    nav_collections: 'Collecties',
    nav_privacy: 'Privacy',
    nav_guide_click: 'Klik voor Gids',
    shop_title: 'Museumwinkel',
    shop_subtitle: 'Haal een kunstwerk in huis',
    shop_intro: 'Hoogwaardige gecertificeerde prints en digitale downloads, van ansichtkaart tot museale Fine Art print.',
    shop_postcard: 'Ansichtkaart',
    shop_poster: 'Poster',
    shop_print: 'Fine Art Print',
    shop_digital: 'Digitale Download',
    shop_order_now: 'Nu Bestellen',
    shop_order_form: 'Bestelformulier',
    shop_add_to_cart: 'In Winkelwagen',
    shop_details: 'Product Details',
    shop_format: 'Formaat',
    shop_price: 'Prijs',
    shop_order_success: 'Bestelling Ontvangen',
    shop_order_desc: 'Bedankt voor uw bestelling. Wij nemen via e-mail contact met u op voor de afhandeling en verzending.',
    shop_setting_up: 'De winkel wordt momenteel ingericht',
    shop_come_back_soon: 'Kom binnenkort terug voor de collectie gecertificeerde prints en digitale downloads',
    shop_back_to_shop: 'Terug naar de winkel',
    shop_quality_notice: 'Elke gecertificeerde print wordt met uiterste zorg vervaardigd op museum-gekwalificeerd papier dat de kleurechtheid tientallen jaren garandeert.',
    shop_payment_notice: 'Betaling vindt plaats via factuur na bevestiging.',
    order_label_name: 'Naam',
    order_label_email: 'E-mail',
    order_label_address: 'Adres & Postcode',
    order_button_confirm: 'Bevestig Bestelling',
    footer_rights: 'Alle rechten voorbehouden.',
    hero_start_walk: 'Begin de Wandeling',
    hero_your_room: 'Stel uw eigen zaal samen',
    hero_subtitle: 'Digitale Collectie',
    gallery_select: 'Kies een Zaal',
    gallery_closed: 'Deze zaal is momenteel niet toegankelijk.',
    curator_title: 'Uw eigen expositie',
    curator_subtitle: 'Curator van het Retrospectief',
    curator_clear: 'Filters wissen',
    curator_open: 'Open Zaal',
    curator_other: 'Overig',
    curator_no_results: 'Geen werken gevonden voor deze combinatie.',
    viewer_room: 'Zaal',
    viewer_unknown_year: 'Jaartal onbekend',
    viewer_prev: 'Vorige',
    viewer_next: 'Volgende',
    viewer_show_info: 'Toon informatie',
    viewer_hide_info: 'Verberg informatie',
    viewer_unknown: 'Interactief',
    viewer_hint_zoom: 'Scroll of dubbelklik voor vrije zoom',
    end_of_room: 'Einde van deze zaal',
    prev_room: 'Vorige Zaal',
    next_room: 'Volgende Zaal',
    all_works: 'Alle werken',
    contact_label_name: 'Naam',
    contact_label_email: 'E-mail',
    contact_label_subject: 'Onderwerp',
    contact_label_message: 'Bericht / Herinnering',
    contact_button_send: 'Verstuur Bericht',
    contact_phone: 'Telefoon',
    contact_location: 'Locatie',
    contact_loc_value: 'Nederland',
    contact_success_title: 'Bericht Verzonden',
    contact_success_desc: 'Bedankt voor uw bericht. We nemen zo snel mogelijk contact met u op.',
    guide_welcome: 'Handleiding & Concept',
    guide_intro: 'Welkom in het Digitaal Retrospectief. Dit museum is een levend archief waar de kunst van Thijs Sterk op nieuwe manieren ontsloten wordt.',
    guide_concept_title: 'Het Museumconcept',
    guide_concept_desc: 'De collectie wordt aangeboden in twee vormen: Vaste Zalen (gecureerde thema\'s) en Wisselende Collecties die u zelf kunt samenstellen.',
    guide_rooms_title: 'Vaste & Wisselende Zalen',
    guide_rooms_desc: 'Via het menu \'Zalen\' bezoekt u onze permanente collecties. Deze zijn zorgvuldig ingericht rondom specifieke thema\'s uit het leven van Sterk.',
    guide_curator_manual_title: 'Zelf Ontsluiten: Uw Eigen Zaal',
    guide_curator_step1: '1. Ga naar \'Uw Zaal\': Hier bent u de curator. U krijgt toegang tot het volledige archief.',
    guide_curator_step2: '2. Gebruik Tags: Selecteer filters zoals Periode, Techniek of Plaats om dwarsdoorsneden te maken.',
    guide_curator_step3: '3. Open Zaal: Klik op de knop om uw persoonlijke selectie te bekijken in de Deep Zoom viewer.',
    guide_nav_title: 'Navigatie',
    guide_nav_tour_label: 'De Tour',
    guide_nav_tour_desc: 'Een meeslepende wandeling door de zalen. Gebruik de pijltjestoetsen om virtueel te lopen.',
    guide_viewer_title: 'De Deep Zoom Viewer',
    guide_viewer_zoom_label: 'Detail focus',
    guide_viewer_zoom_desc: 'Gebruik de +/- knop of scroll om in te zoomen tot op de verfkorrel.',
    guide_controls_title: 'Bediening',
    guide_controls_esc: 'Sluiten',
    guide_controls_arrows: 'Wandelen',
    guide_controls_scroll: 'Vrij inzoomen',
    guide_controls_click: 'Klik voor details',
    guide_footer: 'Ontdek de essentie van licht en ruimte.',
  },
  en: {
    nav_home: 'Home',
    nav_tour: 'Tour',
    nav_galleries: 'Galleries',
    nav_your_room: 'Your Room',
    nav_shop: 'Shop',
    nav_about: 'About',
    nav_contact: 'Contact',
    nav_admin: 'Admin',
    nav_museum_title: 'Digital Museum',
    nav_collections: 'Collections',
    nav_privacy: 'Privacy',
    nav_guide_click: 'Click for Guide',
    shop_title: 'Museum Shop',
    shop_subtitle: 'Bring art into your home',
    shop_intro: 'High-quality certified prints and digital downloads, from postcards to museum Fine Art prints.',
    shop_postcard: 'Postcard',
    shop_poster: 'Poster',
    shop_print: 'Fine Art Print',
    shop_digital: 'Digital Download',
    shop_order_now: 'Order Now',
    shop_order_form: 'Order Form',
    shop_add_to_cart: 'Add to Cart',
    shop_details: 'Product Details',
    shop_format: 'Format',
    shop_price: 'Price',
    shop_order_success: 'Order Received',
    shop_order_desc: 'Thank you for your order. We will contact you via email for payment and shipping.',
    shop_setting_up: 'The shop is currently being set up',
    shop_come_back_soon: 'Come back soon for the collection of certified prints and digital downloads',
    shop_back_to_shop: 'Back to the shop',
    shop_quality_notice: 'Each certified print is manufactured with the utmost care on museum-qualified paper.',
    shop_payment_notice: 'Payment takes place via invoice after confirmation.',
    order_label_name: 'Name',
    order_label_email: 'Email',
    order_label_address: 'Address & Postal Code',
    order_button_confirm: 'Confirm Order',
    footer_rights: 'All rights reserved.',
    hero_start_walk: 'Start the Walk',
    hero_your_room: 'Curate your own room',
    hero_subtitle: 'Digital Collection',
    gallery_select: 'Choose a Gallery',
    gallery_closed: 'This gallery is currently closed.',
    curator_title: 'Your own exhibition',
    curator_subtitle: 'Curator of the Retrospective',
    curator_clear: 'Clear filters',
    curator_open: 'Open Room',
    curator_other: 'Other',
    curator_no_results: 'No works found for this combination.',
    viewer_room: 'Room',
    viewer_unknown_year: 'Year unknown',
    viewer_prev: 'Previous',
    viewer_next: 'Next',
    viewer_show_info: 'Show information',
    viewer_hide_info: 'Hide information',
    viewer_unknown: 'Interactive',
    viewer_hint_zoom: 'Scroll or double-click for free zoom',
    end_of_room: 'End of this gallery',
    prev_room: 'Previous Room',
    next_room: 'Next Room',
    all_works: 'All works',
    contact_label_name: 'Name',
    contact_label_email: 'Email',
    contact_label_subject: 'Subject',
    contact_label_message: 'Message / Memory',
    contact_button_send: 'Send Message',
    contact_phone: 'Phone',
    contact_location: 'Location',
    contact_loc_value: 'The Netherlands',
    contact_success_title: 'Message Sent',
    contact_success_desc: 'Thank you for your message. We will contact you as soon as possible.',
    guide_welcome: 'Manual & Concept',
    guide_intro: 'Welcome to the Digital Retrospective. This museum is a living archive where Thijs Sterk\'s art is unlocked in new ways.',
    guide_concept_title: 'The Museum Concept',
    guide_concept_desc: 'The collection is offered in two forms: Fixed Rooms (curated themes) and Changing Collections that you can assemble yourself.',
    guide_rooms_title: 'Fixed & Rotating Rooms',
    guide_rooms_desc: 'Visit our curated permanent collections via the \'Galleries\' menu, carefully arranged around specific themes.',
    guide_curator_manual_title: 'Unlock Art: Your Own Room',
    guide_curator_step1: '1. Go to \'Your Room\': Here you are the curator. You get access to the full archive.',
    guide_curator_step2: '2. Use Tags: Select filters such as Period, Technique, or Location to create cross-sections.',
    guide_curator_step3: '3. Open Room: Click the button to view your personal selection in the Deep Zoom viewer.',
    guide_nav_title: 'Navigation',
    guide_nav_tour_label: 'The Tour',
    guide_nav_tour_desc: 'An immersive walk through the rooms. Use the arrow keys to walk virtually.',
    guide_viewer_title: 'Deep Zoom Viewer',
    guide_viewer_zoom_label: 'Detail focus',
    guide_viewer_zoom_desc: 'Use the +/- button or scroll to zoom in down to the grain of the paint.',
    guide_controls_title: 'Controls',
    guide_controls_esc: 'Close',
    guide_controls_arrows: 'Walk',
    guide_controls_scroll: 'Free zoom',
    guide_controls_click: 'Click for details',
    guide_footer: 'Discover the essence of light and space.',
  },
  de: {
    nav_home: 'Home',
    nav_tour: 'Tour',
    nav_galleries: 'Galerien',
    nav_your_room: 'Ihr Saal',
    nav_shop: 'Laden',
    nav_about: 'Über',
    nav_contact: 'Kontakt',
    nav_admin: 'Admin',
    nav_museum_title: 'Digitales Museum',
    nav_guide_click: 'Hier klicken für Hilfe',
    shop_title: 'Museumsshop',
    shop_subtitle: 'Holen Sie sich Kunst nach Hause',
    shop_intro: 'Hochwertige zertifizierte Drucke und digitale Downloads, von Postkarten bis hin zu Kunstdrucken.',
    shop_postcard: 'Postkarte',
    shop_poster: 'Poster',
    shop_print: 'Kunstdruck',
    shop_digital: 'Digitaler Download',
    shop_order_now: 'Jetzt Bestellen',
    shop_order_success: 'Bestellung erhalten',
    shop_setting_up: 'Der Shop wordt momenteel ingericht',
    shop_come_back_soon: 'Besuchen Sie uns bald wieder für zertifizierte Drucke und digitale Downloads',
    shop_back_to_shop: 'Zurück zum Laden',
    shop_quality_notice: 'Jeder zertifizierte Druck wird mit größter Sorgfalt auf museal qualifiziertem Papier hergestellt.',
    shop_payment_notice: 'Die Zahlung erfolgt nach Bestätigung per Rechnung.',
    footer_rights: 'Alle Rechte vorbehalten.',
    hero_start_walk: 'Wanderung beginnen',
    hero_subtitle: 'Digitale Sammlung',
    curator_other: 'Andere',
    all_works: 'Alle Werke',
    guide_welcome: 'Anleitung & Konzept',
    guide_intro: 'Willkommen in der digitalen Retrospektive. Dieses Museum ist ein lebendiges Archiv, in dem die Kunst von Thijs Sterk auf neue Weise erschlossen wird.',
    guide_concept_title: 'Das Museumskonzept',
    guide_concept_desc: 'Die Sammlung wird in zwei Formen angeboten: Feste Säle (kuratierte Themen) und wechselnde Sammlungen, die Sie selbst zusammenstellen können.',
    guide_rooms_title: 'Feste & Wechselnde Säle',
    guide_rooms_desc: 'Besuchen Sie unsere permanenten Kollektionen über das Menü \'Galerien\', die sorgfältig nach Themen geordnet sind.',
    guide_curator_manual_title: 'Kunst selbst erschließen',
    guide_curator_step1: '1. Gehen Sie zu \'Ihr Saal\': Hier sind Sie der Kurator und haben Zugriff auf das gesamte Archiv.',
    guide_curator_step2: '2. Tags verwenden: Wählen Sie Filter wie Periode, Technik oder Ort aus.',
    guide_curator_step3: '3. Saal öffnen: Klicken Sie auf die Schaltfläche, um Ihre persönliche Auswahl im Deep Zoom Viewer anzuzeigen.',
    guide_nav_title: 'Navigation',
    guide_nav_tour_label: 'Die Tour',
    guide_nav_tour_desc: 'Ein immersiver Rundgang. Nutzen Sie die Pfeiltasten zum Gehen.',
    guide_viewer_title: 'Deep Zoom Viewer',
    guide_viewer_zoom_label: 'Detailfokus',
    guide_viewer_zoom_desc: 'Nutzen Sie die +/- Taste oder scrollen Sie, um bis zum Pinselstrich heranzuzoomen.',
    guide_controls_title: 'Bedienung',
    guide_controls_esc: 'Schließen',
    guide_controls_arrows: 'Gehen',
    guide_controls_scroll: 'Freies Zoomen',
    guide_controls_click: 'Details zeigen',
    guide_footer: 'Entdecken Sie die Essenz von Licht und Raum.',
  },
  fr: {
    nav_home: 'Accueil',
    nav_tour: 'Visite',
    nav_galleries: 'Salles',
    nav_your_room: 'Votre Salle',
    nav_shop: 'Boutique',
    nav_about: 'À propos',
    nav_contact: 'Contact',
    nav_admin: 'Admin',
    nav_museum_title: 'Musée Digital',
    nav_guide_click: 'Guide du Musée',
    shop_title: 'Boutique du Musée',
    shop_subtitle: 'L\'art s\'invite chez vous',
    shop_intro: 'Impressions certifiées et téléchargements numériques de haute qualité.',
    shop_postcard: 'Carte postale',
    shop_poster: 'Poster',
    shop_print: 'Impression d\'art',
    shop_digital: 'Téléchargement numérique',
    shop_order_now: 'Commander',
    shop_setting_up: 'La boutique est en cours d\'aménagement',
    shop_come_back_soon: 'Revenez bientôt pour les impressions certifiées et téléchargements numériques',
    shop_back_to_shop: 'Retour à la boutique',
    shop_quality_notice: 'Chaque impression certifiée est fabriquée avec le plus grand soin.',
    shop_payment_notice: 'Le paiement s\'effectue par facture après confirmation.',
    footer_rights: 'Tous droits réservés.',
    hero_start_walk: 'Commencer la visite',
    hero_subtitle: 'Collection numérique',
    curator_other: 'Autre',
    all_works: 'Toutes les œuvres',
    guide_welcome: 'Manuel & Concept',
    guide_intro: 'Bienvenue dans la Rétrospective Digitale. Ce musée est une archive vivante où l\'art de Thijs Sterk est révélé de manière innovante.',
    guide_concept_title: 'Le Concept du Musée',
    guide_concept_desc: 'La collection est proposée sous deux formes : Salles Fixes (thèmes curatés) et Collections Changeantes que vous composez vous-même.',
    guide_rooms_title: 'Salles Fixes & Tournantes',
    guide_rooms_desc: 'Visitez nos collections permanentes via le menu \'Salles\', soigneusement organisées autour de thèmes spécifiques.',
    guide_curator_manual_title: 'Créez votre propre salle',
    guide_curator_step1: '1. Allez à \'Votre Salle\' : Ici, vous êtes le conservateur. Vous accédez à l\'archive complète.',
    guide_curator_step2: '2. Utilisez les Tags : Sélectionnez des filtres comme Période, Technique ou Lieu.',
    guide_curator_step3: '3. Ouvrir la Salle : Cliquez sur le bouton pour voir votre sélection personnelle avec le Deep Zoom.',
    guide_nav_title: 'Navigation',
    guide_nav_tour_label: 'La Visite',
    guide_nav_tour_desc: 'Une promenade immersive. Utilisez les flèches pour vous déplacer virtuellement.',
    guide_viewer_title: 'Le Visionneur Deep Zoom',
    guide_viewer_zoom_label: 'Focus sur les détails',
    guide_viewer_zoom_desc: 'Utilisez le bouton +/- ou le scroll pour zoomer jusqu\'au grain de la peinture.',
    guide_controls_title: 'Commandes',
    guide_controls_esc: 'Fermer',
    guide_controls_arrows: 'Marcher',
    guide_controls_scroll: 'Zoom libre',
    guide_controls_click: 'Cliquer pour détails',
    guide_footer: 'Découvrez l\'essence de la lumière et de l\'espace.',
  },
  es: {
    nav_home: 'Inicio',
    nav_tour: 'Visita',
    nav_galleries: 'Galerías',
    nav_your_room: 'Su Sala',
    nav_shop: 'Tienda',
    nav_about: 'Acerca de',
    nav_contact: 'Contacto',
    nav_admin: 'Admin',
    nav_museum_title: 'Museo Digital',
    nav_guide_click: 'Guía del Museo',
    shop_title: 'Tienda del Museo',
    shop_subtitle: 'Lleve el arte a su hogar',
    shop_intro: 'Impresiones certificadas y descargas digitales de alta calidad.',
    shop_postcard: 'Postal',
    shop_poster: 'Póster',
    shop_print: 'Impresión de arte',
    shop_digital: 'Descarga digital',
    shop_order_now: 'Pedir ahora',
    shop_setting_up: 'La tienda se está configurando actualmente',
    shop_come_back_soon: 'Vuelva pronto para ver las impresiones certificadas y descargas digitales',
    shop_back_to_shop: 'Volver a la tienda',
    shop_quality_notice: 'Cada impresión certificada se fabrica con el máximo cuidado.',
    shop_payment_notice: 'El pago se realiza mediante factura tras la confirmación.',
    footer_rights: 'Todos los derechos reservados.',
    hero_start_walk: 'Iniciar la Visita',
    hero_subtitle: 'Colección Digital',
    curator_other: 'Otro',
    all_works: 'Todas las obras',
    guide_welcome: 'Manual y Concepto',
    guide_intro: 'Bienvenido a la Retrospectiva Digital. Este museo es un archivo vivo donde el arte de Thijs Sterk se descubre de formas nuevas.',
    guide_concept_title: 'El Concepto del Museo',
    guide_concept_desc: 'La colección se ofrece en dos formas: Salas Fijas (temas curados) y Colecciones Cambiantes que usted mismo puede organizar.',
    guide_rooms_title: 'Salas Fijas y Rotativas',
    guide_rooms_desc: 'Visite nuestras colecciones permanentes a través del menú \'Galerías\', organizadas por temas específicos.',
    guide_curator_manual_title: 'Organice su propia sala',
    guide_curator_step1: '1. Vaya a \'Su Sala\': Aquí usted es el curador y tiene acceso al archivo completo.',
    guide_curator_step2: '2. Use Etiquetas: Seleccione filtros como Período, Técnica o Lugar.',
    guide_curator_step3: '3. Abrir Sala: Haga clic en el botón para ver su selección personal en el visor Deep Zoom.',
    guide_nav_title: 'Navegación',
    guide_nav_tour_label: 'La Visita',
    guide_nav_tour_desc: 'Un paseo inmersivo. Use las flechas para caminar virtualmente.',
    guide_viewer_title: 'Visor Deep Zoom',
    guide_viewer_zoom_label: 'Enfoque de detalle',
    guide_viewer_zoom_desc: 'Use el botón +/- o el scroll para ver hasta el grano de la pintura.',
    guide_controls_title: 'Controles',
    guide_controls_esc: 'Cerrar',
    guide_controls_arrows: 'Caminar',
    guide_controls_scroll: 'Zoom libre',
    guide_controls_click: 'Clic para detalles',
    guide_footer: 'Descubra la esencia de la luz y el espacio.',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('nl');

  useEffect(() => {
    const saved = localStorage.getItem('app-lang') as Language;
    if (saved && ['nl', 'en', 'de', 'fr', 'es'].includes(saved)) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app-lang', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || translations['nl'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
