'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'nl' | 'en' | 'de' | 'fr' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  nl: {
    nav_home: 'Home',
    nav_tour: 'Tour',
    nav_galleries: 'Zalen',
    nav_your_room: 'Uw Zaal',
    nav_shop: 'Winkel',
    nav_about: 'Over',
    nav_contact: 'Contact',
    nav_admin: 'Beheer',
    nav_museum_title: 'Digitaal Museum',
    nav_collections: 'Collecties',
    nav_privacy: 'Privacy',
    nav_guide_click: 'Klik voor Gids',
    shop_title: 'Museumwinkel',
    shop_subtitle: 'Haal een kunstwerk in huis',
    shop_intro: 'Hoogwaardige gecertificeerde prints en digitale downloads, van ansichtkaart tot museale Fine Art print.',
    shop_postcard: 'Ansichtkaart',
    shop_poster: 'Poster',
    shop_print: 'Fine Art Print',
    shop_digital: 'Digitale Download',
    shop_order_now: 'Nu Bestellen',
    shop_order_form: 'Bestelformulier',
    shop_add_to_cart: 'In Winkelwagen',
    shop_details: 'Product Details',
    shop_format: 'Formaat',
    shop_price: 'Prijs',
    shop_order_success: 'Bestelling Ontvangen',
    shop_order_desc: 'Bedankt voor uw bestelling. Wij nemen via e-mail contact met u op voor de afhandeling en verzending.',
    shop_setting_up: 'De winkel wordt momenteel ingericht',
    shop_come_back_soon: 'Kom binnenkort terug voor de collectie gecertificeerde prints en digitale downloads',
    shop_back_to_shop: 'Terug naar de winkel',
    shop_quality_notice: 'Elke gecertificeerde print wordt met uiterste zorg vervaardigd op museum-gekwalificeerd papier dat de kleurechtheid tientallen jaren garandeert.',
    shop_payment_notice: 'Betaling vindt plaats via factuur na bevestiging.',
    shop_placeholder_name: 'Uw volledige naam',
    shop_placeholder_email: 'uw@email.nl',
    shop_placeholder_address: 'Straat, huisnummer, postcode en stad',
    order_label_name: 'Naam',
    order_label_email: 'E-mail',
    order_label_address: 'Adres & Postcode',
    order_button_confirm: 'Bevestig Bestelling',
    footer_rights: 'Alle rechten voorbehouden.',
    hero_start_walk: 'Begin de Wandeling',
    hero_your_room: 'Stel uw eigen zaal samen',
    hero_subtitle: 'Digitale Collectie',
    gallery_select: 'Kies een Zaal',
    gallery_closed: 'Deze zaal is momenteel niet toegankelijk.',
    curator_title: 'Uw eigen expositie',
    curator_subtitle: 'Curator van het Retrospectief',
    curator_clear: 'Filters wissen',
    curator_open: 'Open Zaal',
    curator_other: 'Overig',
    curator_no_results: 'Geen werken gevonden voor deze combinatie.',
    viewer_room: 'Zaal',
    viewer_unknown_year: 'Jaartal onbekend',
    viewer_prev: 'Vorige',
    viewer_next: 'Volgende',
    viewer_show_info: 'Toon informatie',
    viewer_hide_info: 'Verberg informatie',
    viewer_unknown: 'Interactief',
    viewer_hint_zoom: 'Scroll of dubbelklik voor vrije zoom',
    end_of_room: 'Einde van deze zaal',
    prev_room: 'Vorige Zaal',
    next_room: 'Volgende Zaal',
    all_works: 'Alle werken',
    contact_label_name: 'Naam',
    contact_label_email: 'E-mail',
    contact_label_subject: 'Onderwerp',
    contact_label_message: 'Bericht / Herinnering',
    contact_button_send: 'Verstuur Bericht',
    contact_phone: 'Telefoon',
    contact_location: 'Locatie',
    contact_loc_value: 'Nederland',
    contact_success_title: 'Bericht Verzonden',
    contact_success_desc: 'Bedankt voor uw bericht. We nemen zo snel mogelijk contact met u op.',
    contact_placeholder_name: 'Uw naam',
    contact_placeholder_email: 'uw@email.nl',
    contact_placeholder_subject: 'Waar gaat het over?',
    contact_placeholder_message: 'Uw verhaal of vraag...',
    guide_welcome: 'Welkom in het Digitaal Retrospectief',
    guide_intro: 'Dit museum is een levend archief. Een plek waar kunst wordt bewaard voor de toekomst in de hoogste resolutie.',
    guide_concept_title: 'Het Concept',
    guide_concept_quote: '"Dit platform ontsluit collecties in museale kwaliteit, waarbij elk detail tot op de verfkorrel bestudeerd kan worden via onze Deep Zoom technologie."',
    guide_nav_title: 'Navigatie Gids',
    guide_nav_tour_label: 'De Tour',
    guide_nav_tour_desc: 'Een meeslepende wandeling door de zalen. Gebruik uw muis of pijltjestoetsen om te lopen.',
    guide_nav_galleries_label: 'Zalen',
    guide_nav_galleries_desc: 'Directe toegang tot de thematische zalen.',
    guide_nav_curator_label: 'Curator',
    guide_nav_curator_desc: 'Stel uw eigen expositie samen op basis van tags.',
    guide_nav_shop_label: 'Winkel',
    guide_nav_shop_desc: 'Haal kunst in huis: van posters tot gecertificeerde prints en digitale downloads.',
    guide_viewer_title: 'De Viewer',
    guide_viewer_zoom_label: 'Deep Zoom (+/-)',
    guide_viewer_zoom_desc: 'Zoom direct 5x in op de kleinste details van het schilderij.',
    guide_viewer_info_label: 'Informatie (i)',
    guide_viewer_info_desc: 'Toont details zoals jaartal, techniek en afmetingen.',
    guide_viewer_browse_label: 'Bladeren',
    guide_viewer_browse_desc: 'Gebruik de pijlen om door de collectie te wandelen.',
    guide_controls_title: 'Bediening',
    guide_controls_esc: 'Sluiten',
    guide_controls_arrows: 'Wandelen',
    guide_controls_scroll: 'Vrij inzoomen',
    guide_controls_click: 'Detail focus',
    guide_footer: 'Bewaard voor de toekomst.',
    asset_guide_title: 'Aanlevergids voor de Artiest',
    asset_guide_subtitle: 'Hoe bereidt u uw werken voor op museale Deep Zoom kwaliteit?',
    asset_specs_title: 'Technische Specificaties',
    asset_specs_pixels: 'Minimaal 4000 pixels aan de langste zijde.',
    asset_specs_format: 'Bestandstype: Hoge kwaliteit JPEG of WebP.',
    asset_specs_color: 'Kleurprofiel: sRGB voor optimale kleurgetrouwheid.',
    asset_manual_title: 'Digitalisering stappenplan',
    asset_manual_step1: '1. Fotografie: Gebruik een statief en indirect daglicht voor een egaal beeld zonder schaduwen.',
    asset_manual_step2: '2. Apparatuur: Een moderne camera is ideaal, maar high-end smartphones in \'Pro\' modus volstaan vaak ook.',
    asset_manual_step3: '3. Nabewerking: Wij verzorgen de Deep Zoom verwerking; lever simpelweg het Master-bestand aan.',
    asset_faq_title: 'Veelgestelde Vragen',
    asset_faq_q1: 'Waarom 4000 pixels?',
    asset_faq_a1: 'Alleen met deze resolutie kunnen bezoekers inzoomen tot op de penseelstreek zonder kwaliteitsverlies.',
    asset_faq_q2: 'Wat als mijn foto\'s kleiner zijn?',
    asset_faq_a2: 'Kleine foto\'s worden wazig bij inzoomen. We adviseren om belangrijke werken opnieuw te laten fotograferen.',
    asset_faq_q3: 'Moet ik zelf Deep Zoom tegels maken?',
    asset_faq_a3: 'Nee, onze infrastructuur doet dit automatisch. Lever gewoon het origineel aan.',
  },
  en: {
    nav_home: 'Home',
    nav_tour: 'Tour',
    nav_galleries: 'Galleries',
    nav_your_room: 'Your Room',
    nav_shop: 'Shop',
    nav_about: 'About',
    nav_contact: 'Contact',
    nav_admin: 'Admin',
    nav_museum_title: 'Digital Museum',
    nav_collections: 'Collections',
    nav_privacy: 'Privacy',
    nav_guide_click: 'Click for Guide',
    shop_title: 'Museum Shop',
    shop_subtitle: 'Bring art into your home',
    shop_intro: 'High-quality certified prints and digital downloads, from postcards to museum Fine Art prints.',
    shop_postcard: 'Postcard',
    shop_poster: 'Poster',
    shop_print: 'Fine Art Print',
    shop_digital: 'Digital Download',
    shop_order_now: 'Order Now',
    shop_order_form: 'Order Form',
    shop_add_to_cart: 'Add to Cart',
    shop_details: 'Product Details',
    shop_format: 'Format',
    shop_price: 'Price',
    shop_order_success: 'Order Received',
    shop_order_desc: 'Thank you for your order. We will contact you via email for payment and shipping.',
    shop_setting_up: 'The shop is currently being set up',
    shop_come_back_soon: 'Come back soon for the collection of certified prints and digital downloads',
    shop_back_to_shop: 'Back to the shop',
    shop_quality_notice: 'Each certified print is manufactured with the utmost care on museum-qualified paper.',
    shop_payment_notice: 'Payment takes place via invoice after confirmation.',
    shop_placeholder_name: 'Your full name',
    shop_placeholder_email: 'your@email.com',
    shop_placeholder_address: 'Street, house number, zip code and city',
    order_label_name: 'Name',
    order_label_email: 'Email',
    order_label_address: 'Address & Postal Code',
    order_button_confirm: 'Confirm Order',
    footer_rights: 'All rights reserved.',
    hero_start_walk: 'Start the Walk',
    hero_your_room: 'Curate your own room',
    hero_subtitle: 'Digital Collection',
    gallery_select: 'Choose a Gallery',
    gallery_closed: 'This gallery is currently closed.',
    curator_title: 'Your own exhibition',
    curator_subtitle: 'Curator of the Retrospective',
    curator_clear: 'Clear filters',
    curator_open: 'Open Room',
    curator_other: 'Other',
    curator_no_results: 'No works found for this combination.',
    viewer_room: 'Room',
    viewer_unknown_year: 'Year unknown',
    viewer_prev: 'Previous',
    viewer_next: 'Next',
    viewer_show_info: 'Show information',
    viewer_hide_info: 'Hide information',
    viewer_unknown: 'Interactive',
    viewer_hint_zoom: 'Scroll or double-click for free zoom',
    end_of_room: 'End of this gallery',
    prev_room: 'Previous Room',
    next_room: 'Next Room',
    all_works: 'All works',
    contact_label_name: 'Name',
    contact_label_email: 'Email',
    contact_label_subject: 'Subject',
    contact_label_message: 'Message / Memory',
    contact_button_send: 'Send Message',
    contact_phone: 'Phone',
    contact_location: 'Location',
    contact_loc_value: 'The Netherlands',
    contact_success_title: 'Message Sent',
    contact_success_desc: 'Thank you for your message. We will contact you as soon as possible.',
    contact_placeholder_name: 'Your name',
    contact_placeholder_email: 'your@email.com',
    contact_placeholder_subject: 'What is it about?',
    contact_placeholder_message: 'Your story or question...',
    guide_welcome: 'Welcome to the Digital Retrospective',
    guide_intro: 'This museum is a living archive. A place where art is preserved for the future in high resolution.',
    guide_concept_title: 'The Concept',
    guide_concept_quote: '"This platform unlocks collections in museum quality, where every detail can be studied down to the grain of paint via our Deep Zoom technology."',
    guide_nav_title: 'Navigation Guide',
    guide_nav_tour_label: 'The Tour',
    guide_nav_tour_desc: 'An immersive walk through the galleries. Use your mouse or arrow keys.',
    guide_nav_galleries_label: 'Galleries',
    guide_nav_galleries_desc: 'Direct access to thematic collections.',
    guide_nav_curator_label: 'Curator',
    guide_nav_curator_desc: 'Curate your own exhibition using tags.',
    guide_nav_shop_label: 'Shop',
    guide_nav_shop_desc: 'Bring art home: from posters to certified prints and digital downloads.',
    guide_viewer_title: 'The Viewer',
    guide_viewer_zoom_label: 'Deep Zoom (+/-)',
    guide_viewer_zoom_desc: 'Zoom in 5x instantly on the smallest details.',
    guide_viewer_info_label: 'Information (i)',
    guide_viewer_info_desc: 'Shows details like year, technique, and dimensions.',
    guide_viewer_browse_label: 'Browse',
    guide_viewer_browse_desc: 'Use arrows to walk through the collection.',
    guide_controls_title: 'Controls',
    guide_controls_esc: 'Close',
    guide_controls_arrows: 'Walk',
    guide_controls_scroll: 'Free Zoom',
    guide_controls_click: 'Detail focus',
    guide_footer: 'Preserved for the future.',
    asset_guide_title: 'Asset Delivery Guide for Artists',
    asset_guide_subtitle: 'How to prepare your work for museum Deep Zoom quality?',
    asset_specs_title: 'Technical Specifications',
    asset_specs_pixels: 'Minimum 4000 pixels on the longest side.',
    asset_specs_format: 'File type: High-quality JPEG or WebP.',
    asset_specs_color: 'Color profile: sRGB for optimal fidelity.',
    asset_manual_title: 'Digitization Roadmap',
    asset_manual_step1: '1. Photography: Use a tripod and indirect daylight for even lighting.',
    asset_manual_step2: '2. Equipment: Modern DSLRs are ideal, but high-end phones in \'Pro\' mode work well too.',
    asset_manual_step3: '3. Processing: We handle the Deep Zoom conversion; just provide the Master file.',
    asset_faq_title: 'Frequently Asked Questions',
    asset_faq_q1: 'Why 4000 pixels?',
    asset_faq_a1: 'Only at this resolution can viewers zoom down to the brushstroke without quality loss.',
    asset_faq_q2: 'What if my photos are smaller?',
    asset_faq_a2: 'Small photos become blurry when zooming. We recommend re-shooting important works.',
    asset_faq_q3: 'Do I need to make Deep Zoom tiles myself?',
    asset_faq_a3: 'No, our infrastructure handles this automatically. Just provide the original.',
  },
  de: {
    nav_home: 'Home',
    nav_tour: 'Tour',
    nav_galleries: 'Galerien',
    nav_your_room: 'Ihr Saal',
    nav_shop: 'Laden',
    nav_about: 'Über',
    nav_contact: 'Kontakt',
    nav_admin: 'Admin',
    nav_museum_title: 'Digitales Museum',
    nav_guide_click: 'Hier klicken für Hilfe',
    shop_title: 'Museumsshop',
    shop_subtitle: 'Holen Sie sich Kunst nach Hause',
    shop_intro: 'Hochwertige zertifizierte Drucke und digitale Downloads, von Postkarten bis hin zu Kunstdrucken.',
    shop_postcard: 'Postkarte',
    shop_poster: 'Poster',
    shop_print: 'Kunstdruck',
    shop_digital: 'Digitaler Download',
    shop_order_now: 'Jetzt Bestellen',
    shop_order_success: 'Bestellung erhalten',
    shop_setting_up: 'Der Shop wird derzeit eingerichtet',
    shop_come_back_soon: 'Besuchen Sie uns bald wieder für zertifizierte Drucke und digitale Downloads',
    shop_back_to_shop: 'Zurück zum Laden',
    shop_quality_notice: 'Jeder zertifizierte Druck wird mit größter Sorgfalt auf museal qualifiziertem Papier hergestellt.',
    shop_payment_notice: 'Die Zahlung erfolgt nach Bestätigung per Rechnung.',
    footer_rights: 'Alle Rechte vorbehalten.',
    hero_start_walk: 'Wanderung beginnen',
    hero_subtitle: 'Digitale Sammlung',
    curator_other: 'Andere',
    all_works: 'Alle Werke',
    guide_welcome: 'Willkommen in der Digitalen Retrospektive',
    guide_intro: 'Dieses Museum ist ein lebendiges Archiv. Ein Ort, an dem Kunst für die Zukunft bewahrt wird.',
    guide_concept_title: 'Das Konzept',
    guide_concept_quote: '"Diese Plattform macht Sammlungen in Museumsqualität zugänglich, wobei jedes Detail mit Deep Zoom studiert werden kann."',
    guide_nav_title: 'Navigationshilfe',
    guide_nav_tour_label: 'Die Tour',
    guide_nav_tour_desc: 'Ein immersiver Rundgang durch die Säle.',
    guide_nav_galleries_label: 'Galerien',
    guide_nav_galleries_desc: 'Direkter Zugang zu Sammlungen.',
    guide_nav_curator_label: 'Kurator',
    guide_nav_curator_desc: 'Stellen Sie Ihre eigene Ausstellung zusammen.',
    guide_nav_shop_label: 'Laden',
    guide_nav_shop_desc: 'Holen Sie sich Kunst nach Hause.',
    guide_viewer_title: 'Der Viewer',
    guide_viewer_zoom_label: 'Deep Zoom (+/-)',
    guide_viewer_zoom_desc: 'Zoomt direkt 5-fach in kleinste Details.',
    guide_viewer_info_label: 'Info (i)',
    guide_viewer_info_desc: 'Zeigt Jahr, Technik und Maße an.',
    guide_viewer_browse_label: 'Blättern',
    guide_viewer_browse_desc: 'Verwenden Sie die Pfeile zum Navigieren.',
    guide_controls_title: 'Bedienung',
    guide_controls_esc: 'Schließen',
    guide_controls_arrows: 'Wandern',
    guide_controls_scroll: 'Freies Zoomen',
    guide_controls_click: 'Detail-Fokus',
    guide_footer: 'Für die Zukunft bewahrt.',
    asset_guide_title: 'Anlieferungsleitfaden',
    asset_guide_subtitle: 'Wie bereiten Sie Ihre Werke für Museumsqualität vor?',
    asset_specs_title: 'Technische Daten',
    asset_specs_pixels: 'Mindestens 4000 Pixel an der längsten Seite.',
    asset_specs_format: 'Dateityp: Hochwertiges JPEG oder WebP.',
    asset_specs_color: 'Profil: sRGB für optimale Anzeige.',
    asset_manual_title: 'Schritt-für-Schritt',
    asset_manual_step1: '1. Fotografie: Nutzen Sie Stativ und indirektes Licht.',
    asset_manual_step2: '2. Kamera: Moderne Kameras sind ideal, High-End-Smartphones oft ausreichend.',
    asset_manual_step3: '3. Verarbeitung: Wir erstellen die Deep Zoom Kacheln automatisch.',
    asset_faq_title: 'Häufige Fragen',
    asset_faq_q1: 'Warum 4000 Pixel?',
    asset_faq_a1: 'Nur so kann man bis zum Pinselstrich heranzoomen.',
    asset_faq_q2: 'Was, wenn Fotos kleiner sind?',
    asset_faq_a2: 'Diese werden beim Zoomen unscharf. Wir empfehlen Neuaufnahmen.',
    asset_faq_q3: 'Muss ich Kacheln selbst machen?',
    asset_faq_a3: 'Nein, das macht unsere Software. Senden Sie das Original.',
  },
  fr: {
    nav_home: 'Accueil',
    nav_tour: 'Visite',
    nav_galleries: 'Salles',
    nav_your_room: 'Votre Salle',
    nav_shop: 'Boutique',
    nav_about: 'À propos',
    nav_contact: 'Contact',
    nav_admin: 'Admin',
    nav_museum_title: 'Musée Digital',
    nav_guide_click: 'Guide du Musée',
    shop_title: 'Boutique du Musée',
    shop_subtitle: 'L\'art s\'invite chez vous',
    shop_intro: 'Impressions certifiées et téléchargements numériques de haute qualité.',
    shop_postcard: 'Carte postale',
    shop_poster: 'Poster',
    shop_print: 'Impression d\'art',
    shop_digital: 'Téléchargement numérique',
    shop_order_now: 'Commander',
    shop_setting_up: 'La boutique est en cours d\'aménagement',
    shop_come_back_soon: 'Revenez bientôt pour les impressions certifiées et téléchargements numériques',
    shop_back_to_shop: 'Retour à la boutique',
    shop_quality_notice: 'Chaque impression certifiée est fabriquée avec le plus grand soin.',
    shop_payment_notice: 'Le paiement s\'effectue par facture après confirmation.',
    footer_rights: 'Tous droits réservés.',
    hero_start_walk: 'Commencer la visite',
    hero_subtitle: 'Collection numérique',
    curator_other: 'Autre',
    all_works: 'Toutes les œuvres',
    guide_welcome: 'Bienvenue dans la Rétrospective Digitale',
    guide_intro: 'Ce musée est une archive vivante. Un lieu où l\'art est préservé pour l\'avenir.',
    guide_concept_title: 'Le Concept',
    guide_concept_quote: '"Cette plateforme rend les collections accessibles en qualité muséale grâce au Deep Zoom."',
    guide_nav_title: 'Guide de Navigation',
    guide_nav_tour_label: 'La Visite',
    guide_nav_tour_desc: 'Une promenade immersive à travers les salles.',
    guide_nav_galleries_label: 'Salles',
    guide_nav_galleries_desc: 'Accès direct aux collections thématiques.',
    guide_nav_curator_label: 'Conservateur',
    guide_nav_curator_desc: 'Composez votre propre exposition.',
    guide_nav_shop_label: 'Boutique',
    guide_nav_shop_desc: 'Rapporter l\'art chez soi : posters et impressions certifiées.',
    guide_viewer_title: 'Le Visionneur',
    guide_viewer_zoom_label: 'Deep Zoom (+/-)',
    guide_viewer_zoom_desc: 'Zoomez 5x instantanément sur les détails.',
    guide_viewer_info_label: 'Infos (i)',
    guide_viewer_info_desc: 'Année, technique et dimensions.',
    guide_viewer_browse_label: 'Parcourir',
    guide_viewer_browse_desc: 'Utilisez les flèches pour naviguer.',
    guide_controls_title: 'Commandes',
    guide_controls_esc: 'Fermer',
    guide_controls_arrows: 'Marcher',
    guide_controls_scroll: 'Zoom libre',
    guide_controls_click: 'Mise au point',
    guide_footer: 'Préservé pour l\'avenir.',
    asset_guide_title: 'Guide pour l\'Artiste',
    asset_guide_subtitle: 'Préparer vos œuvres pour une qualité Deep Zoom muséale.',
    asset_specs_title: 'Spécifications Techniques',
    asset_specs_pixels: 'Minimum 4000 pixels sur le côté le plus long.',
    asset_specs_format: 'Fichier : JPEG haute qualité ou WebP.',
    asset_specs_color: 'Profil : sRGB pour une fidélité optimale.',
    asset_manual_title: 'Guide de Numérisation',
    asset_manual_step1: '1. Photographie : Utilisez un trépied et une lumière naturelle indirecte.',
    asset_manual_step2: '2. Équipement : Caméras modernes ou smartphones haut de gamme.',
    asset_manual_step3: '3. Traitement : Nous gérons la conversion Deep Zoom.',
    asset_faq_title: 'FAQ',
    asset_faq_q1: 'Pourquoi 4000 pixels ?',
    asset_faq_a1: 'Essentiel pour voir chaque coup de pinceau sans flou.',
    asset_faq_q2: 'Et si mes photos sont petites ?',
    asset_faq_a2: 'Le rendu sera flou. Nous conseillons de re-photographier.',
    asset_faq_q3: 'Dois-je créer les tuiles ?',
    asset_faq_a3: 'Non, notre logiciel le fait. Envoyez juste l\'original.',
  },
  es: {
    nav_home: 'Inicio',
    nav_tour: 'Visita',
    nav_galleries: 'Galerías',
    nav_your_room: 'Su Sala',
    nav_shop: 'Tienda',
    nav_about: 'Acerca de',
    nav_contact: 'Contacto',
    nav_admin: 'Admin',
    nav_museum_title: 'Museo Digital',
    nav_guide_click: 'Guía del Museo',
    shop_title: 'Tienda del Museo',
    shop_subtitle: 'Lleve el arte a su hogar',
    shop_intro: 'Impresiones certificadas y descargas digitales de alta calidad.',
    shop_postcard: 'Postal',
    shop_poster: 'Póster',
    shop_print: 'Impresión de arte',
    shop_digital: 'Descarga digital',
    shop_order_now: 'Pedir ahora',
    shop_setting_up: 'La tienda se está configurando actualmente',
    shop_come_back_soon: 'Vuelva pronto para ver las impresiones certificadas y descargas digitales',
    shop_back_to_shop: 'Volver a la tienda',
    shop_quality_notice: 'Cada impresión certificada se fabrica con el máximo cuidado.',
    shop_payment_notice: 'El pago se realiza mediante factura tras la confirmación.',
    footer_rights: 'Todos los derechos reservados.',
    hero_start_walk: 'Iniciar la Visita',
    hero_subtitle: 'Colección Digital',
    curator_other: 'Otro',
    all_works: 'Todas las obras',
    guide_welcome: 'Bienvenido a la Retrospectiva Digital',
    guide_intro: 'Este museo es un archivo vivo. Un lugar donde el arte se preserva para el futuro.',
    guide_concept_title: 'El Concepto',
    guide_concept_quote: '"Esta plataforma hace accesibles las colecciones en calidad de museo mediante Deep Zoom."',
    guide_nav_title: 'Guía de Navegación',
    guide_nav_tour_label: 'La Visita',
    guide_nav_tour_desc: 'Un paseo inmersivo por las salas.',
    guide_nav_galleries_label: 'Galerías',
    guide_nav_galleries_desc: 'Acceso directo a colecciones temáticas.',
    guide_nav_curator_label: 'Conservador',
    guide_nav_curator_desc: 'Organice su propia exposición.',
    guide_nav_shop_label: 'Tienda',
    guide_nav_shop_desc: 'Arte en casa: pósters e impresiones certificadas.',
    guide_viewer_title: 'El Visor',
    guide_viewer_zoom_label: 'Deep Zoom (+/-)',
    guide_viewer_zoom_desc: 'Aumenta 5x al instante los detalles.',
    guide_viewer_info_label: 'Info (i)',
    guide_viewer_info_desc: 'Año, técnica y dimensiones.',
    guide_viewer_browse_label: 'Navegar',
    guide_viewer_browse_desc: 'Use las flechas para navegar.',
    guide_controls_title: 'Controles',
    guide_controls_esc: 'Cerrar',
    guide_controls_arrows: 'Caminar',
    guide_controls_scroll: 'Zoom libre',
    guide_controls_click: 'Enfoque de detalle',
    guide_footer: 'Preservado para el futuro.',
    asset_guide_title: 'Guía para el Artista',
    asset_guide_subtitle: 'Prepare sus obras para calidad Deep Zoom de museo.',
    asset_specs_title: 'Datos Técnicos',
    asset_specs_pixels: 'Mínimo 4000 píxeles en el lado más largo.',
    asset_specs_format: 'Archivo: JPEG de alta calidad o WebP.',
    asset_specs_color: 'Perfil: sRGB para fidelidad óptima.',
    asset_manual_title: 'Plan de Digitalización',
    asset_manual_step1: '1. Fotografía: Use trípode y luz natural indirecta.',
    asset_manual_step2: '2. Equipo: Cámaras modernas o móviles de gama alta.',
    asset_manual_step3: '3. Proceso: Nosotros manejamos la conversión Deep Zoom.',
    asset_faq_title: 'FAQ',
    asset_faq_q1: '¿Por qué 4000 píxeles?',
    asset_faq_a1: 'Esencial para ver cada pincelada sin desenfoque.',
    asset_faq_q2: '¿Y si mis fotos son pequeñas?',
    asset_faq_a2: 'Se verán borrosas. Recomendamos volver a fotografiar.',
    asset_faq_q3: '¿Debo crear los mosaicos?',
    asset_faq_a3: 'No, nuestro software lo hace. Envíe el original.',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('nl');

  useEffect(() => {
    const saved = localStorage.getItem('app-lang') as Language;
    if (saved && ['nl', 'en', 'de', 'fr', 'es'].includes(saved)) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app-lang', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || translations['nl'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
